### ISSUE TITLE
Review of the download format

### ISSUE THREAD

**Issue by peterdesmet** [ices-tools-dev/esas#75]
Current download format is:

```
ESAS_0419581169/
  Disclaimer.txt
  Campaign_0419581169.csv
  Observation_0419581169.csv
  Position_0419581169.csv
  Samples_0419581169.csv
```

- [ ] Use consistent file name (plural), so `Campaigns.csv`, `Observations.csv`, `Positions.csv`, `Samples.csv`.
- [ ] Don't append number to file names, it makes it more difficult to run automated pipelines on data if file names change

## Campaigns

- [ ] Don't include `tblCampaignID`
- [ ] Don't include `DataCustodian`, `DataCustodianContact` (new suggestion in #74)
- [ ] Use ISO date format `YYYY-MM-DD` for `StartDate` and `EndDate`

## Samples

 - [ ] Don't include `tblUploadID`, `tblCampaignID`, `tblSampleID`
 - [ ] Use ISO date format `YYYY-MM-DD` for `Date`

## Positions

 - [ ] Don't include `tblUploadID`, `tblCampaignID`, `tblSampleID`, `tblPositionID`

## Observations

 - [ ] Don't include `tblUploadID`, `tblCampaignID`, `tblSampleID`, `tblPositionID`, `tblObservationID`
 - [ ] Add `AphiaID` and `AphiaScientificName` (see #63)

**Comment by cmspinto** [comment]
Could someone test the current download and give some feed back?

**Comment by peterdesmet** [comment]
👍 Many things resolved. I updated the issue body with some open items, including:

- [ ] Please don't include `T00:00:00` for dates if possible.
- [ ] The four (renamed) additional scientific name fields (see #63 and email)
- [ ] Disclaimer does not seem to reflect ESAS, but VME

**Comment by peterdesmet** [comment]
All reported issues here are resolved, except for `T00:00:00` in startDate/endDate.
